- name: Add Docker repo
  shell: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
  changed_when: false

- name: Install Docker-ce
  yum:
    name: docker-ce
    state: latest

- name: Enable service Docker
  service:
    name: docker
    state: started
    enabled: yes

- name: Install Pip
  yum:
    name: python-pip

- name: Install docker-py
  pip:
    name: docker-py

- name: Get public ip
  uri:
    url: http://ifconfig.me/ip
    return_content: yes
  register: ip_public

- name: Start OpenVPN container
  docker_container:
    name: openvpn
    image: "{{ openvpn_image }}"
    published_ports:
      - "{{ http_port }}:8080"
      - "{{ openvpn_udp_port }}:1194/udp"
    env:
      HOST_ADDR: "{{ ip_public.content }}"
    capabilities:
      - NET_ADMIN

- debug:
    msg: "OpenVPN configuration http://{{ ip_public.content }}"
