- name: Install network manager
  yum:
    name: 'NetworkManager'
    state: installed

- name: nmcli add virtual adapter
  nmcli:
    type: ethernet
    conn_name: '{{ item.conn_name }}'
    ip4: '{{ item.ip4 }}'
    gw4: '{{ item.gw4 }}'
    state: present
  with_items:
    - '{{ nmcli_ethernet }}'

- name: Install StrongSwan
  yum:
    name: strongswan
    state: latest

- name: Generate preShared key
  shell: openssl rand -base64 64
  register: preshared_key

- name: Get public IP
  uri:
    url: http://ifconfig.me/ip
    return_content: yes
  register: ip_local

- name: Create secret file
  template:
    src: ipsec.secrets.j2
    dest: /etc/strongswan/ipsec.secrets

- name: Create config file
  template:
    src: ipsec.conf.j2
    dest: /etc/strongswan/ipsec.conf

- name: Enable service StrongSwan
  service:
    name: strongswan
    state: started
    enabled: yes

- debug:
    msg: "Public IP: {{ ip_local.content }}"
- debug:
    msg: "Preshared key: {{ preshared_key.stdout }}"
